#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# Not found route
not_found:
  path: /{any}
  controller: App\Controller\ErrorController::index
  requirements:
    any: .*

